### ISSUE TITLE
Embedded Mono.Cecil may conflict with UPM version

### ISSUE THREAD

**Issue by MostHated** [active-logic/prolog#20]
Hey there,
  Sorry for yet another post, but I went to import this just now and was met with a ton of Mono.Cecil errors. I see that you have included a copy of it in the asset but since I am using the Entities, Unity.Physics, and Hybrid Renderer, I already have Mono.Cecil installed via the package manager (it installs automatically when you install those). I tried to see if I could remove either the one you included, or the one from the package manager and if I remove yours, I get several errors similar to the following: (I made sure to follow the steps first, deleting the csproj files from the project root)

```
[CompilerError] The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Assets/Prolog/Editor/LoggingAspect.cs:2 column 7

[CompilerError] The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
Compiler Error at Assets/Prolog/Editor/LoggingAspect.cs:60 column 31

``` 
So on and so forth. If I try to remove the one that is installed via the package manager, well, I cannot. It says that it is a requirement for the aforementioned DOTS packages. Does this require the specific Mono.Cecil you included, or can it be adapted to use the one which Unity provides?

Thanks again,
-MH

--- Edit --- 
I tried to see if I could maybe make your file see the already existing one, but I am not quite sure I am doing it correctly. I just looked at some other packages from Unity that were using Mono.Cecil, but perhaps it is a namespace discrepancy or something? I am not sure.

![](https://i.imgur.com/OChMebF.png)

**Comment by eelstork** [comment]
Thanks for reporting, and also investigating this. I looked at this before and it seemed (by default at least) a one way import ('packages' see modules in user space, but user space doesn't see modules in packages). Even if Mono from packages can be used, there's also the case where it wouldn't be here in the first place...
Making Prolog a package would fix it but I need to stop and really look into it, never done this.

**Comment by MostHated** [comment]
Perhaps this might be useful?

https://gist.github.com/LotteMakesStuff/6e02e0ea303030517a071a1c81eb016e

**Comment by eelstork** [comment]
@MostHated yes, it is helpful! I looked further into this and I think we'd like to link as a "local package" as described here:
https://docs.unity3d.com/Manual/CustomPackages.html

Let's give it a try.

**Comment by MostHated** [comment]
I could be mistaken, but it is my understanding that once you make it an actual "package" (as far as Unity is concerned) I believe Unity has a built-in way to grab the files straight from the repo as long as you have the necessary files needed for it to be considered a package, be it local or "remotely hosted".  I don't think you would have to do much else, such as submitting it to the github "package repo" as you would if it were an NPM package or similar. I suppose we shall find out!

**Comment by eelstork** [comment]
Looks fixed; if you update to latest and follow the [new install instructions](https://github.com/active-logic/prolog/blob/master/Readme.md), this should work. 

Notes:
- Referencing fixed using your suggested method, only adding `"overrideReferences": true`
- UPM packaging not 100% required but resolves the dep to Mono.Cecil
- Git repo URL is enough though a community registry would be nicer.

**Comment by MostHated** [comment]
Awesome news. I was able to easily install it now by just adding the line to my project package manifest. :+1: I will try and spend some time and familiarize myself with it, but first thing out of the gate when I attempted to open the log window I was greeted with the errors below. I will have to see if I have those fonts installed out of the box on Linux. 

```cs
[Exception] InvalidOperationException: Sequence contains no elements
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Enumerable.First[TSource]()    <fbb5ed17eb6e46c680000f8910ebb50c>:0

LogWindow.get_font()    Library/PackageCache/com.activ.prolog@30715fd750c4828bbcf40927725e0801cb8f8af7/Editor/LogWindow.cs:147
145:   static Font font{ get{
146:       if(_font) return _font;
-->147:       var avail = new []{ "Menlo", "Consolas", "Courier", "Courier New",
148:                           "Lucida Console", "Monaco", "Inconsolata"      }
149:           .Intersect(Font.GetOSInstalledFontNames()).First();

LogWindow.OnGUI()    Library/PackageCache/com.activ.prolog@30715fd750c4828bbcf40927725e0801cb8f8af7/Editor/LogWindow.cs:72
70:   GUI.backgroundColor = Color.black;
71:   var style = GUI.skin.textArea;
-->72:   var f = font;
73:   if(f == null) Debug.LogError("font not available");
74:   style.font = f;

```

**Comment by eelstork** [comment]
You are probably getting the GUI error because no suitable font is found. For font issues, see
https://github.com/active-logic/prolog/issues/22
For keeping your copy of the lib up to date (or freezing to a stable version), see:
https://github.com/active-logic/prolog/issues/23
My concern here is that based on a git URL, Unity may/not check whether a cached version of the library is up to date; also when rebuilding the cache it would automatically bump users to the latest version, not to mention `master` needn't be stable at all times.
The doc is correct, better put activ windows in a separate menu.

**Comment by eelstork** [comment]
Main issue referred here appears to be fixed. Related issues filed separately
